### ISSUE TITLE
Support TimeSpan

### ISSUE THREAD

**Issue by magmablinker** [nenoNaninu/Tapper#202]
TimeSpan is currently not supported. It would be very nice if it would be possible to get support for TimeSpan
```
1>======== Exception ========
1>System.InvalidOperationException: System.TimeSpan is not supported.
1>   at Tapper.DefaultTypeMapperProvider.GetTypeMapper(ITypeSymbol type)
1>   at Tapper.TypeMappers.TypeMapper.MapTo(ITypeSymbol typeSymbol, ITranspilationOptions options)
```

**Comment by backfromexile** [comment]
Hi there, what type would you expect `TimeSpan` to be transpiled to in TypeScript?
The [Temporal API](https://tc39.es/proposal-temporal/docs/index.html) is still only a proposal only and has no browser support so for. `Date` is not an option imo.  

The only real option I personally see so far is Tapper providing a type for this. However, then Tapper would probably need to provide a type for `DateOnly` and `TimeOnly`, and likely other types as well.

@nenoNaninu some of the TypeScript openapi-generators allow for adding custom type definitions and conversions from and to JSON.
Should we do something similar here? Then Tapper could provide default type definitions and conversions for the aforementioned types, which would also allow for custom extensions by the users.

**Comment by magmablinker** [comment]
For now it would be enough if it would just be translated to a string, similiar to as how TimeSpan is being handled when it's serialized to json. I know this is far from optimal but it would be a better option than not having the ability to use TimeSpan (without manually serializing it as string) at all.

**Comment by backfromexile** [comment]
> For now it would be enough if it would just be translated to a string, similiar to as how TimeSpan is being handled when it's serialized to json. 

The thing is, Tapper also supports MessagePack serialization because it is used for TypedSignalR.
However, I don't think it's much of an issue as there are similar default type mappers [here](https://github.com/nenoNaninu/Tapper/tree/main/src/Tapper/TypeMappers) already.

Feel free to create a PR for this change. 

I think in the future the type mapping and transpilation needs to be reworked again because it's not very flexible at the moment, but adding a mapper for `TimeSpan` should solve your issue for now.

**Comment by nenoNaninu** [comment]
TimeSpan was supported from v1.12.0! Try it!
